"""Turn the splash art into C headers (Claude's Linux helper; output is committed).

Usage: python3 tools/make_splash.py
Reads assets/splash/splash<N>_<W>x<H>.jpg and writes src/assets/splash_<W>x<H>.h
with the JPEG bytes. The images must be baseline (not progressive) JPEGs:
LovyanGFX's decoder draws them block by block straight to the panel, so no
frame buffer is needed. Metadata segments (EXIF, ICC profile, comments) are
dropped; the image data is copied unchanged.
"""
import pathlib
import re
import struct

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "assets" / "splash"
OUT = ROOT / "src" / "assets"


def strip_jpeg(data: bytes) -> bytes:
    if data[:2] != b"\xff\xd8":
        raise SystemExit("not a JPEG")
    out = bytearray(b"\xff\xd8")
    i = 2
    while i < len(data):
        if data[i] != 0xFF:
            raise SystemExit("bad JPEG marker")
        marker = data[i + 1]
        if marker == 0xDA:                      # start of scan: copy the rest
            out += data[i:]
            break
        length = struct.unpack(">H", data[i + 2:i + 4])[0]
        if marker == 0xC2:
            raise SystemExit("progressive JPEG: re-save as baseline")
        keep = not (0xE1 <= marker <= 0xEF or marker == 0xFE)   # keep APP0 (JFIF)
        if keep:
            out += data[i:i + 2 + length]
        i += 2 + length
    return bytes(out)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    sizes = {}
    for f in sorted(SRC.glob("splash*_*x*.jpg")):
        m = re.match(r"splash(\d+)_(\d+)x(\d+)\.jpg$", f.name)
        if m:
            sizes.setdefault((int(m[2]), int(m[3])), []).append((int(m[1]), f))
    for (w, h), files in sorted(sizes.items()):
        lines = [f"// Splash images for {w}x{h} screens. Generated by tools/make_splash.py",
                 "// from assets/splash/ - do not edit.", "#pragma once", "", "#include <cstddef>",
                 "#include <cstdint>", ""]
        names = []
        for n, f in sorted(files):
            data = strip_jpeg(f.read_bytes())
            name = f"kSplash{w}_{n}"
            names.append((name, len(data)))
            lines.append(f"static const uint8_t {name}[{len(data)}] = {{")
            for k in range(0, len(data), 24):
                lines.append("    " + ",".join(str(b) for b in data[k:k + 24]) + ",")
            lines.append("};")
            lines.append("")
            print(f"{f.name}: {f.stat().st_size} -> {len(data)} bytes")
        lines.append("struct SplashImage { const uint8_t* data; size_t len; };")
        lines.append("static const SplashImage kSplashImages[] = {")
        for name, n in names:
            lines.append(f"    {{{name}, {n}}},")
        lines.append("};")
        lines.append("static constexpr int kSplashCount = sizeof kSplashImages / sizeof kSplashImages[0];")
        (OUT / f"splash_{w}x{h}.h").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
