"""Build CYD-dle's word lists (Claude's Linux helper; the output is committed).

Usage: python3 tools/make_words.py
Reads assets/words/:
  enable_5.txt     every five-letter word of ENABLE2K (public domain): what
                   the game accepts as a guess
  scowl35_5.txt    five-letter base words at SCOWL/ESDB size 35, i.e. common
                   words (Kevin Atkinson's ESDB, permissive license, see
                   SCOWL-Copyright.txt): where the answers come from
  blocklist.txt    words never used at all (vulgar, sexual, slurs)
  answers_exclude.txt  accepted as guesses, never the answer (regional words,
                   words not right for children)
Writes src/games/cyddle/cyddle_words.h: answers and the extra accepted
guesses as sorted 25-bit packed words (5 bits per letter, a = 0), so
lookups are a binary search.

Answers also leave out plurals and past tenses (words ending in -s but not
-ss/-us/-is, and in -ed), as word games usually do.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
W = ROOT / "assets" / "words"


def words(name):
    out = []
    for line in (W / name).read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            out.append(line)
    return out


def pack(w):
    v = 0
    for ch in w:
        v = (v << 5) | (ord(ch) - 97)
    return v


def main():
    block = set(words("blocklist.txt"))
    enable = {w for w in words("enable_5.txt") if len(w) == 5 and w.isalpha() and w not in block}
    not_answers = set(words("answers_exclude.txt"))
    common = {w for w in words("scowl35_5.txt") if w in enable and w not in not_answers}

    def answer_ok(w):
        if w.endswith("s") and not w.endswith(("ss", "us", "is")):
            return False
        return not w.endswith("ed")

    answers = sorted(w for w in common if answer_ok(w))
    extra = sorted(enable - set(answers))
    lines = ["// CYD-dle word lists. Generated by tools/make_words.py from assets/words/ - do not edit.",
             "// Answers: common words from Kevin Atkinson's ESDB (SCOWL) size 35,",
             "// Copyright 2000-2026 by Kevin Atkinson (see THIRD_PARTY_NOTICES.md).",
             "// Accepted guesses: ENABLE2K (public domain). Packed 5 bits per letter, a = 0.",
             "#pragma once", "", "#include <cstdint>", ""]
    for name, lst in (("kAnswers", answers), ("kGuesses", extra)):
        lines.append(f"static const uint32_t {name}[{len(lst)}] = {{")
        vals = [pack(w) for w in lst]
        for k in range(0, len(vals), 8):
            lines.append("    " + ", ".join(f"0x{v:07X}" for v in vals[k:k + 8]) + ",")
        lines.append("};")
        lines.append(f"static constexpr int {name}Count = {len(lst)};")
        lines.append("")
    out = ROOT / "src" / "games" / "cyddle" / "cyddle_words.h"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(answers)} answers, {len(extra)} more accepted guesses -> {out}")


if __name__ == "__main__":
    main()
