"""Wheel of CYD's puzzles: assets/wheel/phrases.txt -> src/games/wheel/wheel_phrases.cpp.

Checks every line: "Category|PHRASE", letters A-Z with spaces and ' - & .
only, no word over 12 letters, fits 4 rows of 12 tiles wrapped at spaces
(the same greedy wrap as wheel::wrap()), no repeats. Run from the repo root:
    python3 tools/make_phrases.py
"""
import sys

COLS, ROWS = 12, 4
SRC = "assets/wheel/phrases.txt"
OUT = "src/games/wheel/wheel_phrases.cpp"


def wrap(text):
    rows, cur = [], ""
    for w in text.split(" "):
        if not cur:
            cur = w
        elif len(cur) + 1 + len(w) <= COLS:
            cur += " " + w
        else:
            rows.append(cur)
            cur = w
    rows.append(cur)
    return rows


def main():
    cats, items, seen, bad = [], [], set(), 0
    for n, line in enumerate(open(SRC, encoding="utf-8"), 1):
        line = line.rstrip("\n")
        if not line.strip() or line.startswith("#"):
            continue
        try:
            cat, text = line.split("|")
        except ValueError:
            print("%s:%d: not Category|PHRASE" % (SRC, n)); bad += 1; continue
        problems = []
        if any(not (c.isupper() and c.isascii()) and c not in " '-&." for c in text):
            problems.append("only A-Z, space and ' - & .")
        if "  " in text or text != text.strip():
            problems.append("single spaces only")
        if any(len(w) > COLS for w in text.split(" ")):
            problems.append("a word over %d letters" % COLS)
        if len(wrap(text)) > ROWS:
            problems.append("more than %d rows" % ROWS)
        if text in seen:
            problems.append("repeated")
        if len(cat) > 20:
            problems.append("category name too long")
        if problems:
            print("%s:%d: %s: %s" % (SRC, n, text, ", ".join(problems))); bad += 1; continue
        seen.add(text)
        if cat not in cats:
            cats.append(cat)
        items.append((cats.index(cat), text))
    if bad:
        sys.exit(1)
    out = ["// Wheel of CYD's puzzles. Generated by tools/make_phrases.py from",
           "// assets/wheel/phrases.txt (written for this project, MIT) - edit those, not this.",
           '#include "wheel_core.h"', "", "namespace wheel {", "",
           "const char* const kCategories[] = {"]
    out += ['    "%s",' % c for c in cats]
    out += ["};", "const int kCategoryCount = %d;" % len(cats), "", "const Phrase kPhrases[] = {"]
    out += ['    {%d, "%s"},' % (c, t.replace("\\", "\\\\").replace('"', '\\"')) for c, t in items]
    out += ["};", "const int kPhraseCount = %d;" % len(items), "", "} // namespace wheel", ""]
    open(OUT, "w").write("\n".join(out))
    print("%d puzzles in %d categories -> %s" % (len(items), len(cats), OUT))


main()
